"""LLM request/response schemas (provider-agnostic, no SDK types)."""

from typing import Literal

from pydantic import BaseModel, Field


class LLMMessage(BaseModel):
    """A single message passed to a provider."""

    role: Literal["user", "assistant"] = Field(description="Message role")
    content: str = Field(
        ..., min_length=1, max_length=4000, description="Message content"
    )


class LLMResponse(BaseModel):
    """Text generated by a provider."""

    content: str = Field(
        ..., min_length=1, description="Generated assistant text"
    )
    model: str = Field(..., min_length=1, description="Provider model identifier")
